# 全局默认配置
global:
  enabled: true       # 默认全部启用
  type: command       # 默认类型
  timeout: 1000       # 默认超时 1000毫秒（1秒）

# 插件列表
plugins:
  - name: daily-tool
    enabled: true
    path: ./plugin
    entry: index.js
    type: command     # 这里的配置会覆盖全局的 type
    timeout: 3500     # 这里的超时(3.5s)会覆盖全局的 1000ms
    keywords: ['群打卡']
    prefiex: '#'

  - name: plugin-welcome        # ← 新增
    enabled: true
    path: ./plugin
    entry: inde.js
    type: event
    timeout: 3000